import type { Computer, Lab, MaintenanceRecord, MonthlyReport } from "./types";

export const labsSeed: Lab[] = [
  {
    id: "lab-1",
    labNumber: "LAB001",
    name: "网络安全实验室",
    college: "信息工程学院",
    roomCode: "A-403",
    value: 960000,
    manager: "王老师",
    seatCount: 48,
    notes: "双千兆交换，支持虚拟化实验",
  },
  {
    id: "lab-2",
    labNumber: "LAB002",
    name: "软件开发机房",
    college: "信息工程学院",
    roomCode: "B-201",
    value: 880000,
    manager: "李老师",
    seatCount: 60,
    notes: "配备投影与录播",
  },
  {
    id: "lab-3",
    labNumber: "LAB003",
    name: "软件开发技术实验室",
    college: "软件学院",
    roomCode: "待补充-301",
    value: 0,
    manager: "待指定",
    seatCount: 0,
    notes: "基础信息待补充",
  },
  {
    id: "lab-4",
    labNumber: "LAB004",
    name: "测试技术实验室",
    college: "软件学院",
    roomCode: "待补充-302",
    value: 0,
    manager: "待指定",
    seatCount: 0,
    notes: "基础信息待补充",
  },
  {
    id: "lab-5",
    labNumber: "LAB005",
    name: "数据结构和数据库实验室",
    college: "软件学院",
    roomCode: "待补充-303",
    value: 0,
    manager: "待指定",
    seatCount: 0,
    notes: "基础信息待补充",
  },
  {
    id: "lab-6",
    labNumber: "LAB006",
    name: "游戏开发技术实验室",
    college: "数字孪生产业学院",
    roomCode: "待补充-401",
    value: 0,
    manager: "待指定",
    seatCount: 0,
    notes: "基础信息待补充",
  },
];

export const computersSeed: Computer[] = [
  {
    id: "pc-001",
    labId: "lab-1",
    assetCode: "配置1",
    purchaseDate: "2024-09-01",
    cpu: "Intel i7-12700",
    ram: "32GB",
    storage: "1TB SSD",
    cDriveSize: "240GB",
    gpu: "",
    monitor: "27英寸 2K",
    os: "Windows 11",
    other: "",
    status: "running",
  },
  {
    id: "pc-002",
    labId: "lab-1",
    assetCode: "配置2",
    purchaseDate: "2024-09-01",
    cpu: "Intel i5-12400",
    ram: "16GB",
    storage: "512GB SSD",
    cDriveSize: "180GB",
    gpu: "",
    monitor: "24英寸 1080P",
    os: "Windows 11",
    other: "",
    status: "fault",
  },
  {
    id: "pc-003",
    labId: "lab-2",
    assetCode: "配置1",
    purchaseDate: "2025-03-15",
    cpu: "AMD Ryzen 7 5700G",
    ram: "16GB",
    storage: "512GB SSD",
    cDriveSize: "200GB",
    gpu: "",
    monitor: "24英寸 1080P",
    os: "Ubuntu 24.04",
    other: "",
    status: "idle",
  },
  {
    id: "pc-004",
    labId: "lab-3",
    assetCode: "配置1",
    purchaseDate: "2025-09-20",
    cpu: "Intel i7-13700",
    ram: "32GB",
    storage: "1TB SSD",
    cDriveSize: "256GB",
    gpu: "",
    monitor: "27英寸 4K",
    os: "Windows 11",
    other: "",
    status: "running",
  },
  {
    id: "pc-005",
    labId: "lab-4",
    assetCode: "配置1",
    purchaseDate: "2025-10-10",
    cpu: "Intel i5-13400",
    ram: "16GB",
    storage: "512GB SSD",
    cDriveSize: "200GB",
    gpu: "",
    monitor: "24英寸 1080P",
    os: "Windows 11",
    other: "",
    status: "running",
  },
  {
    id: "pc-006",
    labId: "lab-5",
    assetCode: "配置1",
    purchaseDate: "2026-01-12",
    cpu: "AMD Ryzen 7 7700",
    ram: "32GB",
    storage: "1TB SSD",
    cDriveSize: "256GB",
    gpu: "",
    monitor: "27英寸 2K",
    os: "Ubuntu 24.04",
    other: "",
    status: "idle",
  },
  {
    id: "pc-007",
    labId: "lab-6",
    assetCode: "配置1",
    purchaseDate: "2026-02-08",
    cpu: "Intel i7-14700",
    ram: "64GB",
    storage: "2TB SSD",
    cDriveSize: "512GB",
    gpu: "NVIDIA RTX 4060",
    monitor: "32英寸 4K",
    os: "Windows 11",
    other: "",
    status: "running",
  },
];

export const maintenanceSeed: MaintenanceRecord[] = [
  {
    id: "mr-1",
    computerId: "pc-002",
    computerPosition: "1-10",
    issue: "无法进入系统，怀疑系统盘损坏",
    status: "in_progress",
    reporter: "张工",
    reportDate: "2026-03-12",
  },
  {
    id: "mr-2",
    computerId: "pc-003",
    computerPosition: "2-03",
    issue: "风扇异响",
    status: "done",
    reporter: "王老师",
    reportDate: "2026-03-01",
    resolvedDate: "2026-03-05",
  },
];

export const reportsSeed: MonthlyReport[] = [
  {
    id: "rp-1",
    college: "信息工程学院",
    month: "2026-02",
    equipmentUnits: 320,
    equipmentValue: 1840000,
    usageMinutes: 126000,
    activeMinutes: 92300,
  },
  {
    id: "rp-2",
    college: "信息工程学院",
    month: "2026-03",
    equipmentUnits: 320,
    equipmentValue: 1840000,
    usageMinutes: 138500,
    activeMinutes: 101200,
  },
];
